version: "3"
services:
    app:
        container_name: ci-cd-app
        build:
            dockerfile: Dockerfile_app
            context: .
        ports:
            - "127.0.0.1:${APP_PORT}:5000"
            - "127.0.0.1:5022:22"
        deploy:
            resources:
                limits:
                    cpus: "1"
