FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git=1:2.34.1-1ubuntu1.10 \
    python3=3.10.6-1~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.4

RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP

RUN pip install \
    yapf==0.40.2 \
    pylint==3.1.0 \
    requests==2.31.0 \
    pytest==8.1.1 \
    selenium \


COPY tests ./tests

ENTRYPOINT ["python3", "-m", "http.server", "3000"]