FROM ubuntu:22.04

# Installing packages
RUN apt-get update && apt-get install -y \
    git=1:2.34.1-1ubuntu1.10 \
    python3=3.10.6-1~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.4 \
    wget=1.21.2-2ubuntu1

# Installing google chrome for selenium tests
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

# Cloning project with web application
RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP

# Installing dependencies
RUN pip install \
    yapf==0.40.2 \
    pylint==3.1.0 \
    requests==2.31.0 \
    pytest==8.1.1 \
    selenium==4.19.0 \
    webdriver-manager==4.0.1

# Copying tests files
COPY tests ./tests

# Running the http.server
ENTRYPOINT ["python3", "-m", "http.server", "3000"]